name: nytimes_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # allows to cache images using SQFlite
  cached_network_image: ^2.3.2+1
  # create icon of the app
  flutter_launcher_icons: ^0.8.1
  # library of custom icons
  font_awesome_flutter: ^8.9.0
  # ios functionality
  cupertino_icons: ^1.0.0
  # access file systems 
  path_provider: ^1.6.18
  # state management
  hydrated_bloc: ^6.0.2
  flutter_bloc: ^6.0.6
  # Open URL
  url_launcher: ^5.7.2
  # network helpers
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# app icon installer configuration:
# run: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/